project:
  type: website

website:
  title: "Kendall Melanson Gilbert"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



